# =================================================================
# CatWalk Hub Gateway Configuration
# =================================================================

# =================================================================
# CORE WEB SERVER SETTINGS
# =================================================================

# Port for the web server
port: 4567

# Enable debug logging
debug: false

# Enable authentication for API endpoints
useKeyAuth: true

# API authentication key (CHANGE THIS!)
key: 'change_me_to_secure_random_string'

# Normalize chat messages
normalizeMessages: true

# =================================================================
# HUB GATEWAY SETTINGS
# =================================================================

hub:
  # Whether this server acts as a network hub
  # Set to true ONLY on your lobby server
  enabled: false

  # Unique identifier for this server in the network
  # Examples: "lobby", "survival", "creative", "hub", "beta", "vanilla", "heavy"
  server-id: "unknown"

# =================================================================
# DATABASE SETTINGS (REQUIRED)
# =================================================================

database:
  # MariaDB/MySQL database connection settings
  host: "localhost"
  port: 3306
  name: "catwalk_network"
  username: "catwalk"
  password: "your_secure_password"

  # Connection pool settings
  pool-size: 10
  min-idle: 2

  # Connection timeouts (milliseconds)
  connection-timeout: 30000  # 30 seconds
  idle-timeout: 600000       # 10 minutes
  max-lifetime: 1800000      # 30 minutes

# =================================================================
# NETWORK SETTINGS
# =================================================================

network:
  # Request processing settings
  request-processing:
    # How often to check for new requests (seconds)
    poll-interval: 2

    # Default timeout for proxy requests (seconds)
    default-timeout: 30

    # Maximum number of retries for failed requests
    max-retries: 3

    # Maximum concurrent requests per server
    max-concurrent: 10

  # Cache settings for performance
  cache:
    # How often to refresh network topology cache (seconds)
    refresh-interval: 120

    # Enable local caching of server/addon data
    enabled: true

# =================================================================
# TLS/SSL SETTINGS
# =================================================================

tls:
  # Enable TLS/SSL encryption
  enabled: false

  # Path to keystore file (relative to plugin folder)
  keystore: keystore.jks

  # Keystore password
  keystorePassword: ""

  # Enforce Server Name Indication (SNI)
  sni: false

# =================================================================
# CORS SETTINGS
# =================================================================

# Allowed CORS origins
# Use ["*"] to allow all origins (not recommended for production)
corsOrigins:
  - "*"
  # Examples for production:
  # - "https://yourdomain.com"
  # - "https://dashboard.yourserver.net"
  # - "http://localhost:3000"

# =================================================================
# WEBSOCKET SETTINGS
# =================================================================

# Number of console log lines to buffer for websocket connections
# Set to 0 to disable console streaming
websocketConsoleBuffer: 1000

# =================================================================
# API DOCUMENTATION
# =================================================================

# Disable Swagger UI (set to true to hide API documentation)
disable-swagger: false

# =================================================================
# SECURITY SETTINGS
# =================================================================

# Paths that should be blocked from API access
# Use this to disable specific endpoints
blocked-paths: [ ]
  # Examples:
# - "/v1/server/stop"
# - "/v1/players/*/kick"
# - "/v1/console/*"

# Paths that don't require authentication (whitelist)
# These paths will be accessible without API key
whitelisted-paths:
  - "/swagger*"
  - "/redoc*"
  - "/openapi.json"
  - "/v1/network/*"  # Network endpoints are public for hub discovery
  - "/health"
  # Examples:
  # - "/v1/server/status"
  # - "/v1/stats/summary"