name: CatWalk
main: dev.ua.uaproject.catwalk.CatWalkMain
version: 0.6.2-SNAPSHOT
description: CatWalk is a REST API for Minecraft servers. Originally based on CatWalk but now completely redesigned by THEROER.
authors: [THEROER (CatWalk Rework), phybros (CatWalk Original), ATechAdventurer (CatWalk Original), c1oneman (CatWalk Original), Earlh21 (CatWalk Original), Scarsz (CatWalk Original), au5ton (CatWalk Original), Aberdeener (CatWalk Original), Hedlund01 (CatWalk Original), matteoturini (CatWalk Original), Diddyy (CatWalk Original), Velyn-N (CatWalk Original), srmullaney (CatWalk Original), TimeCoding (CatWalk Original)]
load: STARTUP
api-version: 1.16
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  catwalk:
    description: CatWalk Management Command
    permission: catwalk.admin
