name: build

on:
  push:
  workflow_dispatch:
  create:
    tag: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release_id: ${{ steps.release.outputs.id }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew build shadowJar
    - name: Clean up artifacts
      run: rm -f build/libs/*-plain.jar
    - name: Release
      id: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: "CatWalk ${{ github.ref_name }}"
        body_path: CHANGELOG.md
        draft: true
        files: build/libs/*.jar

  # use a separate step to un-draft the release in case the build fails
  finalize-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.build.outputs.release_id }}
